### PR TITLE
Setup environment variable and format cover letter

### PR DESCRIPTION
**Pull request by gauravtiwari**
### Changelog:
- RedCloth to format cover letter body to make it readable (meantime)
- Dotenv to manage environment variables in development
- Bump ruby version to 2.2.2

### CODE REVIEW

**Comment by danielwestendorf** [comment]
Thanks for the PR! The Addition of RedCloth adds a ton of dependencies which aren't used for anything else. I'd be in favor of something a little more lightweight. The other changes are solid though!

**Comment by gauravtiwari** [comment]
@danielwestendorf Thanks for checking. Yes I agree :( Now implementing something else. I will push the version2 soon.

**Comment by gauravtiwari** [comment]
After receiving success email  and seeing unreadable application, I thought this would be a quick fix to make the cover letter readable.

**Comment by gauravtiwari** [comment]
@danielwestendorf What you think of ActionView?

**Comment by gauravtiwari** [comment]
@danielwestendorf this seems much leaner and back to almost initial codebase except a couple of changes.

- using ```gsub!``` to introduce replace `\n` with `<br/>`
- moved cover formatting to separate method `format_cover`
- indented/cleaned up some HTML tags
- Added strong tag for heading items
- Introduced a `<hr/>` tag inside mail to separate the cover with rest

Looks good?

**Pull request closed without merging**
